version: '3'

services:
  api:
    container_name: pyCRUD
    build: '.'
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: database
      DB_HOST: db
      CACHE_HOST: redis
    depends_on:
      - db
      - redis
    ports:
      - '8080:8080'
    restart: always

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'